### Advertisement Sales prediction using Logistic Regression

## Import Libraries

In [24]:
import pandas as pd
import numpy as np

## Upload dataset :

In [25]:
url="https://raw.githubusercontent.com/PRAVEEN1000-7/Machine-Learning/refs/heads/main/AdSalesPrediction/Ad_Sales_dataset.csv"
dataset = pd.read_csv(url)
dataset

Age  Salary  Status
0      24   34153       1
1      37   96325       1
2      46   32999       0
3      32   75318       1
4      28   20814       1
...   ...     ...     ...
1564   28   79634       1
1565   44   30800       0
1566   22   57823       1
1567   37   83878       0
1568   28   38708       1

[1569 rows x 3 columns]

# Segregate dataset into X (input) & Y (output)

In [26]:
X = dataset.iloc[:,:-1].values
X

array([[   24, 34153],
       [   37, 96325],
       [   46, 32999],
       ...,
       [   22, 57823],
       [   37, 83878],
       [   28, 38708]])

In [27]:
Y = dataset.iloc[:,-1].values
Y

array([1, 1, 0, ..., 1, 0, 1])

## Splitting the dataset for training & testing

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

## Feature Scaling

we scale our data to make all the features contribute equally to the result

* Fit_Tranform : fit method is calculating the mean and variance of each of the feature present in our data.

* Transform : transform method is transforming all the features using the respective mean and variance.

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
print(X_train,X_test)

[[ 1.53359335 -1.48153456]
 [ 1.21521526  0.37584328]
 [-1.3318095   0.35949251]
 ...
 [-0.27054919 -1.45292072]
 [-0.27054919 -0.82393792]
 [-1.6501876   0.64010824]] [[-1.11955744 -1.47288083]
 [-1.43793553 -1.00727527]
 [ 0.89683716 -0.58559067]
 [ 1.00296319 -0.52049199]
 [-1.43793553 -0.99305532]
 [ 0.47233303 -1.54054519]
 [ 0.26008097  0.92063701]
 [ 0.366207    1.24987019]
 [ 1.21521526 -1.01571157]
 [ 0.04782891  0.45507493]
 [ 1.42746732  0.83536078]
 [-1.3318095  -0.70669942]
 [ 1.00296319 -0.74357563]
 [-1.54406156  0.37919171]
 [ 0.6845851  -1.38477801]
 [ 1.32134129 -0.5692399 ]
 [ 0.89683716 -1.35133721]
 [-0.27054919  1.65737833]
 [ 0.6845851   0.77269733]
 [-1.11955744  0.29522007]
 [-0.37667522  0.15780403]
 [ 1.42746732  1.20616667]
 [ 0.26008097  1.45512453]
 [ 1.21521526  0.09383599]
 [-0.48280125 -1.41069572]
 [ 0.6845851  -1.48749216]
 [-1.54406156 -0.19460724]
 [ 0.26008097 -0.30932354]
 [-1.54406156 -0.12285519]
 [-1.01343141 -1.65743579]
 [ 1.10908922  0.09087

## Training

In [31]:
from sklearn.linear_model import  LogisticRegression
model = LogisticRegression(random_state=0)
model.fit(X_train,Y_train)

LogisticRegression(random_state=0)

## Testing

In [32]:
Y_predict = model.predict(X_test)
print("actual output vs predicted output")
print(np.column_stack((Y_predict,Y_test)))

actual output vs predicted output
[[1 0]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [1 0]


## Accuracy

In [33]:
from sklearn.metrics import accuracy_score
print(f"Accuracy of the Model: {format(accuracy_score(Y_test,Y_predict)*100)} %")

Accuracy of the Model: 54.4529262086514 %


## Prediction for whether a new customer will buy the product or not.

In [37]:
try :
  Age = int(input("Enter New Customer Age: "))
  Salary = float(input("Enter New Customer Salary: "))
  newCust = [[Age,Salary]]
  result = model.predict(sc.transform(newCust))

  if result == 1:
    print("The customer is likely to make a purchase based on the given data and predictions.")
  else:
     print("The customer is unlikely to make a purchase based on the given data and predictions.")
except :
  print("Invalid Input,please try again")

Enter New Customer Age: 56
Enter New Customer Salary: 650000
The customer is likely to make a purchase based on the given data and predictions.
